-- 1. Create Tables

-- Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  price REAL NOT NULL,
  category TEXT NOT NULL,
  image_url TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  total_amount REAL NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INTEGER NOT NULL DEFAULT 1,
  price REAL NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Support Requests Table
CREATE TABLE IF NOT EXISTS support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE support_requests ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies

-- Products: Everyone can read
CREATE POLICY "Allow public read access to products" ON products FOR SELECT USING (true);

-- Orders: Users can insert their own orders, and read their own orders
CREATE POLICY "Allow users to insert their own orders" ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Allow users to see their own orders" ON orders FOR SELECT USING (auth.uid() = user_id);

-- Order Items: Users can insert items for their own orders
CREATE POLICY "Allow users to insert order items" ON order_items FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM orders WHERE id = order_id AND user_id = auth.uid()
  )
);

-- Support Requests: Everyone can insert
CREATE POLICY "Allow public to insert support requests" ON support_requests FOR INSERT WITH CHECK (true);

-- 4. Seed Products
INSERT INTO products (title, description, price, category, image_url) VALUES
('MacBook Pro 16" M3 Max', 'The most powerful MacBook ever. Featuring the M3 Max chip, 32GB Unified Memory, and a stunning 16-inch Liquid Retina XDR display.', 3499.0, 'Laptops', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80'),
('iPhone 15 Pro Titanium', 'Forged in titanium. Featuring the groundbreaking A17 Pro chip and a more versatile Pro camera system.', 999.0, 'Smartphones', 'https://images.unsplash.com/photo-1592890288564-76628a30a657?auto=format&fit=crop&w=800&q=80'),
('Sony WH-1000XM5', 'Industry-leading noise cancellation. Two processors control 8 microphones for unprecedented noise cancellation.', 398.0, 'Audio', 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80'),
('Apple Watch Ultra 2', 'The ultimate sports and adventure watch. Featuring a 3000-nit display and the most accurate GPS in a sports watch.', 799.0, 'Wearables', 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80'),
('Samsung Galaxy Watch 6', 'Know your health inside and out. Featuring advanced sleep coaching and personalized heart rate zones.', 299.0, 'Wearables', 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80'),
('Garmin Epix Pro (Gen 2)', 'The ultimate high-performance smartwatch. Featuring a stunning AMOLED display and advanced training metrics.', 899.0, 'Wearables', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80'),
('Fujifilm X-T5 Mirrorless', 'A classic design with modern performance. 40.2MP X-Trans CMOS 5 HR sensor and 6.2K/30p video.', 1699.0, 'Cameras', 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80'),
('Dell UltraSharp 32" 4K', 'Experience world-class performance on this 31.5" 4K monitor with wide color coverage and USB-C connectivity.', 849.0, 'Monitors', 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80'),
('Keychron Q1 Mechanical Keyboard', 'A fully customizable 75% layout mechanical keyboard. CNC aluminum body and hot-swappable switches.', 169.0, 'Accessories', 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=800&q=80'),
('Logitech MX Master 3S', 'The iconic mouse remastered. Now with 8K DPI tracking and Quiet Clicks for ultimate precision.', 99.0, 'Accessories', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&q=80'),
('iPad Pro 12.9" M2', 'Astonishing performance. Incredibly advanced displays. The ultimate iPad experience with M2 chip.', 1099.0, 'Tablets', 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80'),
('Sonos Era 300', 'Next-level audio that hits from every direction. Feel more connected with realistic spatial audio.', 449.0, 'Audio', 'https://images.unsplash.com/photo-1589003077984-894e133dabab?auto=format&fit=crop&w=800&q=80'),
('PlayStation 5 Slim', 'Experience lightning-fast loading with an ultra-high speed SSD and deeper immersion with haptic feedback.', 499.0, 'Gaming', 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80'),
('Kindle Scribe', 'The first Kindle for reading and writing. Featuring a 10.2" 300 ppi Paperwhite display.', 339.0, 'Tablets', 'https://images.unsplash.com/photo-1592434134753-a70baf7979d7?auto=format&fit=crop&w=800&q=80'),
('Samsung Galaxy S24 Ultra', 'The ultimate Galaxy experience. Featuring a stunning 6.8" display and 200MP main sensor.', 1299.0, 'Smartphones', 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80'),
('Nintendo Switch OLED', 'Play at home on the TV or on-the-go with a vibrant 7-inch OLED screen and 64GB storage.', 349.0, 'Gaming', 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?auto=format&fit=crop&w=800&q=80'),
('DJI Mini 4 Pro', 'The most advanced mini drone to date. Featuring omnidirectional obstacle sensing and 4K HDR video.', 759.0, 'Drones', 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=800&q=80'),
('Bose QuietComfort Ultra', 'World-class noise cancellation and breakthrough spatialized audio for more immersive listening.', 429.0, 'Audio', 'https://images.unsplash.com/photo-1545127398-14699f92334b?auto=format&fit=crop&w=800&q=80'),
('Razer DeathAdder V3 Pro', 'Victory takes on a new shape. Refined and reforged with the aid of top esports pros.', 149.0, 'Accessories', 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80'),
('GoPro HERO12 Black', 'Incredible image quality and even better HyperSmooth video stabilization for the ultimate action cam.', 399.0, 'Cameras', 'https://images.unsplash.com/photo-1565992441121-4367c2967103?auto=format&fit=crop&w=800&q=80'),
('Microsoft Surface Pro 9', 'The power of a laptop, the flexibility of a tablet. Featuring a 13" PixelSense touchscreen.', 999.0, 'Tablets', 'https://images.unsplash.com/photo-1585915907451-09a4739988e9?auto=format&fit=crop&w=800&q=80'),
('Sonos Move 2', 'The powerful, portable speaker with up to 24 hours of battery life and stereo sound.', 449.0, 'Audio', 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66ba3?auto=format&fit=crop&w=800&q=80'),
('Philips Hue Starter Kit', 'Transform your home with smart lighting. Choose from millions of colors to create the perfect ambiance.', 199.0, 'Smart Home', 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80'),
('Elgato Stream Deck MK.2', '15 customizable LCD keys to control your apps and tools. Instantly trigger actions with a single tap.', 149.0, 'Accessories', 'https://images.unsplash.com/photo-1626767066804-033366e4663b?auto=format&fit=crop&w=800&q=80'),
('LG C3 65" 4K OLED TV', 'Experience the ultimate in picture quality with self-lit pixels and perfect black contrast.', 1599.0, 'Home Theater', 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80'),
('Sonos Arc Soundbar', 'Bring all your entertainment to life with the extraordinary sound of Arc, featuring Dolby Atmos.', 899.0, 'Audio', 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80'),
('Ring Video Doorbell Pro 2', 'Premium wired video doorbell with Head-to-Toe HD+ Video and 3D Motion Detection.', 249.0, 'Smart Home', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=800&q=80'),
('Nest Learning Thermostat', 'The thermostat that learns the temperatures you like and programs itself to help you save energy.', 249.0, 'Smart Home', 'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?auto=format&fit=crop&w=800&q=80'),
('Kindle Paperwhite', 'Now with a 6.8" display and thinner borders, adjustable warm light, and up to 10 weeks of battery life.', 139.0, 'Tablets', 'https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&w=800&q=80'),
('ASUS ROG Rapture GT-AX11000', 'The world’s first 10 Gigabit Wi-Fi router with a quad-core processor and 2.5G gaming port.', 449.0, 'Networking', 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80'),
('Samsung T7 Shield 2TB', 'Rugged, durable, and fast. The T7 Shield gives you superior performance on the go.', 179.0, 'Storage', 'https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?auto=format&fit=crop&w=800&q=80'),
('Nanoleaf Shapes Triangles', 'Modular LED light panels that combine smart technology and sleek ultra-thin design.', 199.0, 'Smart Home', 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80'),
('SteelSeries Arctis Nova Pro', 'The ultimate gaming headset with high-fidelity audio and active noise cancellation.', 349.0, 'Gaming', 'https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=800&q=80'),
('WD Black SN850X 2TB', 'Crush load times and slash throttling with the WD_BLACK SN850X NVMe SSD.', 159.0, 'Storage', 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80'),
('TP-Link Deco XE75 Mesh', 'Whole home mesh Wi-Fi 6E system. Eliminate weak signal areas with high-speed Wi-Fi.', 399.0, 'Networking', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc51?auto=format&fit=crop&w=800&q=80'),
('Blue Yeti USB Microphone', 'The world’s #1 USB microphone for podcasting, game streaming, and YouTube.', 129.0, 'Audio', 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80'),
('Razer Kiyo Pro', 'FHD USB webcam with high-performance adaptive light sensor for superior imaging.', 199.0, 'Accessories', 'https://images.unsplash.com/photo-1612350007145-66b818b28e8e?auto=format&fit=crop&w=800&q=80'),
('Oculus Quest 3', 'The most powerful Quest yet. Breakthrough mixed reality that lets you blend virtual elements with your physical space.', 499.0, 'Gaming', 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&w=800&q=80'),
('DJI Osmo Pocket 3', 'The all-new Pocket 3 features a powerful 1-inch CMOS sensor that puts detail-rich imaging right in the palm of your hand.', 519.0, 'Cameras', 'https://images.unsplash.com/photo-1552160753-117159821e01?auto=format&fit=crop&w=800&q=80'),
('Withings Body Scan', 'The most advanced smart scale ever. Segmental body composition, heart rate, and vascular age.', 399.0, 'Wearables', 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80'),
('Google Pixel Watch 3', 'The best of Google and Fitbit. Featuring advanced health tracking and seamless integration with Pixel.', 349.0, 'Wearables', 'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?auto=format&fit=crop&w=800&q=80');
